### ISSUE TITLE
Repairs on failures with 100% operation reduction and no replacement do not return the subsystem to the correct state

### ISSUE THREAD

**Issue by hrnorton** [WISDEM/WOMBAT#140]
When a failure occurs with a 100% operation reduction, but does not require a replacement, the repair does not return the subsystem to operational and instead the subsystem remains broken for the entire simulation.

A more detailed description of the behavior can be found here : https://forums.nrel.gov/t/wombat-shut-down-i-e-100-operation-reduction-without-replacement/6552

**Comment by RHammond2** [comment]
Hi @hrnorton, thanks for your patience here, this one was a little tricky. I've just opened PR #143, please let me know if this resolves your issue, or if there's something different you're needing for this fix. There is still one lingering bug I have to resolve before I can merge all the changes into main and create the 0.9.4 release, but this gets it pretty close.

**Comment by hrnorton** [comment]
Thanks very much! I haven't been able to completely verify the fix yet (long story involving environment conflicts to get new polars functionality, I'm not sure when I'll have time to work through it properly in light of my own circumstances) but I'm totally happy for you to close the issue as needed on the basis of your own testing.

**Comment by RHammond2** [comment]
Thanks, @hrnorton, on my end it seems to be working just fine, and I was able to add in another related fix at the same time over the last week or so. I'll keep this open but label it as closed until the next release of WOMBAT as it'll only be fixed in the develop branch. If anything else comes up regarding this issue until the release, feel free to use the issue to let me know.
